#Programma  „Kā rūpēties par bruņurupuci?” izveidota, lai pārbaudītu un atgādinātu tās lietotājiem, kas jāzina pirms iegādājas, vai pieskata bruņurupuci. Tev tiks uzdoti 10 jautājumi, ar kuru palīdzību spēsi novērtēt, vai esi gatavs uzņemties rūpes par bruņurupuci. 
print("Cik bieži jābaro bruņurupucis?")
print("A - 3 reizes dienā")
print("B - Reizi dienā")
print("C - Reizi nedēļā")
print("D - 6 reizes nedēļā")
a=int(input("1. jautājuma atbilde - "))
if a==4: print("Malacis!")
else: print("Nē! Pareizā atbilde ir D - 6 reizes nedēļā.")
print("No kā sastāv bruņurupuča pamatuzturs?")
print("A - Tādu pašu, ko ēd cilvēks")
print("B - Augu produktiem")
print("C - Gaļu, zivīm")
print("D - Tikai augļiem")
b=int(input("2. jautājuma atbilde - "))
if b==2: print("Malacis!")
else: print("Nē! Pareizā atbilde ir B - augu produktiem .")
print("Vai bruņurupucim vajadzīgi vitamīni?")
print("A - Jā")
print("B - Nē")
print("C - Tikai ja tas ir saslimis")
c=int(input("3. jautājuma atbilde - "))
if c==2: print("Malacis!")
else: print("Nē! Pareizā atbilde ir A - Bruņurupucim nepeciešami vitamīni arī ikdienā, kā mums, cilvēkiem .")
print("Kas no minētā bruņurupucim ir vajadzīgs?")
print("A - Terārijs")
print("B - Sildošā lampa")
print("C - Smiltis")
print("D - Viss iepriekš minētais")
d=int(input("4. jautājuma atbilde - "))
if d==4: print("Malacis!")
else: print("Nē! Pareizā atbilde ir D - Bruņurupucim nepeciešams viss iepriekš minētais .")
print("Ko bruņurupuči dara ziemā?")
print("A - Guļ ziemas miegu ")
print("B - Ēd vairāk pārtikas ")
print("C - Ir ļoti aktīvi")
print("D - To pašu, ko citos gadalaikos")
e=int(input("5. jautājuma atbilde - "))
if e==4: print("Malacis!")
else: print("Nē! Pareizā atbilde ir A - Bruņurupucim nepeciešams atpūtas laiks - ziemas miegs .")
print("Cik bieži bruņurupucis jāmazgā?")
print("A - Reizi dienā?")
print("B - Reizi nedēļā")
print("C - Katru otro dienu")
print("D - Tad, kad palicis netīrs")
f=int(input("6. jautājuma atbilde - "))
if f==2: print("Malacis!")
else: print("Nē! Pareizā atbilde ir B - Bruņurupucis jāmazgā reizi nedēļā .")
print("A - Trauksmainība")
print("B - Košana cilvēkam")
print("C - Atteikšanās no pārtikas")
print("D - Visi iepriekš minētie")
g=int(input("7. jautājuma atbilde - "))
if g==3: print("Malacis!")
else: print("Nē! Pareizā atbilde ir C - Bruņurupucis mēdz attekties no pārtikas .")
print("Ko nedrīkst dot bruņurupucim?")
print("A - Dzert ūdeni")
print("B - Augļus")
print("C - Kalciju")
print("D - Gaļu")
h=int(input("8. jautājuma atbilde - "))
if h==1: print("Malacis!")
else: print("Nē! Pareizā atbilde ir A - Cik dīvaini tas neliktos, bet bruņurupucim nedrīkst dot dzert ūdeni  .")
print("Ar kādu lampu bruņurupucis jāsilda?")
print("A - Ultravioletu staru")
print("B - Infrasarkano staru")
print("C - Abām minētajām")
i=int(input("9. jautājuma atbilde - "))
if i==3: print("Malacis!")
else: print("Nē! Pareizā atbilde ir C - Bruņurupucim nepeciešamas abas lampas.")
print("Kas ir interesants par bruņurupuču uzbūvi?")
print("A -Nav ribas ")
print("B - Nav mēles")
print("C - Nav zobu")
print("D - Viss iepriekš minētais")
j=int(input("10. jautājuma atbilde - "))
if j==3: print("Malacis!")
else: print("Nē! Pareizā atbilde ir C - Bruņurupucim nav zobu .")