print("Programma „Kā rūpēties par bruņurupuci?” Tev palīdzēs saprast un atcerēties, kas jāzina pirms pieskata bruņurupuci.")
print("Tev tiks uzdoti 10 jautājumi, ar kuru palīdzību spēsi novērtēt, vai esi gatavs uzņemties rūpes.")
print("No piedāvātajiem atbilžu variantiem, izvēlies vienu un ieraksti atbilstošo ciparu.")
print("Cik bieži jābaro bruņurupucis?")
print("1. 3 reizes dienā")
print("2. Reizi dienā")
print("3. Reizi nedēļā")
print("4. 6 reizes nedēļā")
a=int(input("1. jautājuma atbilde - "))
if a==4: print("Malacis!")
else: print("Nē! Pareizā atbilde ir 4. 6 reizes nedēļā.")
print("No kā sastāv bruņurupuča pamatuzturs?")
print("1. No tā, ko ēd cilvēks")
print("2. Augu produktiem")
print("3. Gaļu, zivīm")
print("4. Tikai augļiem")
b=int(input("2. jautājuma atbilde - "))
if b==2: print("Malacis!")
else: print("Nē! Pareizā atbilde ir 2. Augu produktiem .")
print("Vai bruņurupucim vajadzīgi vitamīni?")
print("1. Jā")
print("2. Nē")
print("3. Tikai tad, ja tas ir saslimis")
c=int(input("3. jautājuma atbilde - "))
if c==2: print("Malacis!")
else: print("Nē! Pareizā atbilde ir 1. Bruņurupucim nepieciešami vitamīni arī ikdienā, tāpat kā mums, cilvēkiem .")
print("Kas no minētā bruņurupucim ir vajadzīgs?")
print("1. Terārijs")
print("2. Sildošā lampa")
print("3. Smiltis")
print("4. Viss iepriekš minētais")
d=int(input("4. jautājuma atbilde - "))
if d==4: print("Malacis!")
else: print("Nē! Pareizā atbilde ir 4. Bruņurupucim nepeciešams viss iepriekš minētais .")
print("Ko bruņurupuči dara ziemā?")
print("1. Guļ ziemas miegu ")
print("2. Ēd vairāk pārtikas ")
print("3. Ir ļoti aktīvi")
print("4. - To pašu, ko citos gadalaikos")
e=int(input("5. jautājuma atbilde - "))
if e==4: print("Malacis!")
else: print("Nē! Pareizā atbilde ir 1. Bruņurupucim nepieciešams atpūtas laiks - ziemas miegs .")
print("Cik bieži bruņurupucis jāmazgā?")
print("1. Reizi dienā")
print("2. Reizi nedēļā")
print("3. Katru otro dienu")
print("4. Tad, kad palicis netīrs")
f=int(input("6. jautājuma atbilde - "))
if f==2: print("Malacis!")
else: print("Nē! Pareizā atbilde ir 2. Bruņurupucis jāmazgā reizi nedēļā .")
print("1. Trauksmainība")
print("2. Košana cilvēkam")
print("3. Atteikšanās no pārtikas")
print("4. Visi iepriekš minētie")
g=int(input("7. jautājuma atbilde - "))
if g==3: print("Malacis!")
else: print("Nē! Pareizā atbilde ir 3. Ja bruņurupucis ilgu laiku atsakās no pārtikas .")
print("Ko nedrīkst dot bruņurupucim?")
print("1. Dzert ūdeni")
print("2. Augļus")
print("3. Kalciju")
print("4. Gaļu")
h=int(input("8. jautājuma atbilde - "))
if h==1: print("Malacis!")
else: print("Nē! Pareizā atbilde ir 1. Lai arī, cik dīvaini tas neliktos, bruņurupucim nedrīkst dot dzert ūdeni .")
print("Ar kādu lampu bruņurupucis jāsilda?")
print("1. Ultravioletu staru")
print("2. Infrasarkano staru")
print("3. Abām minētajām")
i=int(input("9. jautājuma atbilde - "))
if i==3: print("Malacis!")
else: print("Nē! Pareizā atbilde ir 3. Bruņurupucim nepeciešamas abas lampas.")
print("Kas ir interesants par bruņurupuču uzbūvi?")
print("1. Nav ribas ")
print("2. Nav mēles")
print("3. Nav zobu")
print("4. Viss iepriekš minētais")
j=int(input("10. jautājuma atbilde - "))
if j==3: print("Malacis!")
else: print("Nē! Pareizā atbilde ir 3. Bruņurupucim nav zobu .")
